/**
 * components/rjesenja/rentACarCopy.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Sav tekst rent-a-car landing stranice, na oba jezika, na jednom mjestu.
 *
 * Zašto ovdje a ne u lib/i18n.ts: sve sekcije sajta drže svoj tekst uz sebe
 * (i18n.ts se više nigdje ne koristi), pa nova stranica prati istu konvenciju.
 * Fajl je običan TS bez "use client", pa ga može čitati i server komponenta
 * (metadata i JSON-LD) i klijentske sekcije.
 *
 * Pravila teksta: bez fraza, bez crtica, obraćanje vlasniku firme, riječ
 * "sistem" ili "aplikacija" umjesto "web stranica".
 */

export type RcCopy = typeof COPY.bs;

export const COPY = {
  bs: {
    meta: {
      title: "Rezervacioni sistem za rent-a-car firme | mehiccdev",
      description:
        "Web aplikacija za rent a car: kalendar dostupnosti po vozilu, admin panel za flotu i cijene i forma za rezervaciju. Sistem za iznajmljivanje vozila, građen u Mostaru.",
    },
    nav: [
      { id: "problem",    label: "Problem" },
      { id: "rjesenje",   label: "Rješenje" },
      { id: "kako-radi",  label: "Kako radi" },
      { id: "case-study", label: "Primjer" },
      { id: "paketi",     label: "Paketi" },
      { id: "poredjenje", label: "Poređenje" },
      { id: "upit",       label: "Upit" },
      { id: "pitanja",    label: "Pitanja" },
    ],
    hero: {
      eyebrow: "Rješenje za rent-a-car firme",
      h1a: "Rezervacioni sistem",
      h1b: "za vašu rent-a-car firmu",
      sub: "Sajt, admin panel i kalendar dostupnosti u jednom. Gost sam provjeri šta je slobodno i pošalje rezervaciju, vi je potvrdite iz panela.",
      ctaPrimary: "Zatražite ponudu",
      ctaSecondary: "Pogledajte cijene",
      points: ["Bez duplih termina", "Radi i van radnog vremena", "Sistem ostaje vaš"],
      demo: {
        window: "vasa-firma.ba", calendar: "Dostupnost, jul",
        car: "VW Golf 8", price: "60 KM / dan",
        free: "Slobodno", booked: "Rezervisano",
        newRequest: "Novi upit", requestBody: "Rezervacija 10 do 13. jula, preuzimanje Mostar",
        confirm: "Potvrdi", confirmed: "Potvrđeno", decline: "Odbij",
      },
    },
    problem: {
      label: "Kako to danas izgleda",
      heading1: "Poznato vam je",
      headingAccent: "ovo",
      items: [
        { t: "Rezervacije stižu na Viber i telefon", d: "Dogovaranje ide kroz prepisku, a podaci o gostima i terminima ostaju razbacani po porukama i sveskama." },
        { t: "Agregatori uzimaju proviziju", d: "Svaka rezervacija preko njih smanjuje zaradu, a gost ostaje njihov klijent, ne vaš." },
        { t: "Upiti van radnog vremena ostaju bez odgovora", d: "Gost koji piše u jedanaest uveče do jutra najčešće nađe drugu firmu." },
        { t: "Dupli termini na istom vozilu", d: "Kada se dostupnost vodi ručno, isto vozilo se lako obeća dvojici gostiju." },
      ],
    },
    solution: {
      label: "Šta sistem radi",
      heading1: "Jedan sistem umjesto",
      headingAccent: "sveske i prepiske",
      items: [
        { t: "Dvojezični sajt", d: "Domaći i strani gosti čitaju ponudu na svom jeziku, bez prevodilaca i objašnjavanja." },
        { t: "Kalendar dostupnosti po vozilu", d: "Sistem sam blokira zauzete termine, pa duplih rezervacija nema." },
        { t: "Admin panel za flotu i cijene", d: "Vozila, cijene, slike i sezonske korekcije mijenjate sami, bez zvanja developera." },
        { t: "Forma za rezervaciju", d: "Gost šalje upit s datumima i lokacijom, vi ga potvrđujete u dva klika." },
        { t: "Upravljanje po lokacijama", d: "Više poslovnica, svaka sa svojom flotom i mjestom preuzimanja." },
        { t: "SEO i brzina", d: "Stranica se otvara brzo i Google je lako pronađe, pa vas nalaze i gosti koji vas ne poznaju." },
      ],
    },
    flow: {
      label: "Kako to izgleda u praksi",
      heading1: "Sistem radi,",
      headingAccent: "vi samo odlučujete",
      sub: "Od upita do potvrđene rezervacije sistem odradi svaki korak sam. Na vama su samo dvije stvari: prihvatite ili odbijete rezervaciju, i blokirajte vozilo kada vam zatreba.",
      bySystem: "Sistem",
      byYou: "Vi",
      steps: [
        { by: "system", t: "Gost bira vozilo i datume", d: "Sistem prikazuje samo ona vozila koja su stvarno slobodna u tom terminu, pa gost ne može tražiti zauzeto." },
        { by: "system", t: "Upit odmah stiže vama", d: "Obavijest na email i telefon, s vozilom, datumima, lokacijom i kontaktom gosta. Bez prepisivanja i traženja po porukama." },
        { by: "you",    t: "Prihvatite ili odbijete", d: "Jedan klik u panelu. To je cijeli vaš posao oko jedne rezervacije." },
        { by: "system", t: "Ostalo se dogodi samo", d: "Termin se zaključa, vozilo nestaje iz ponude za te datume, gost dobija potvrdu na email, a kalendar se ažurira." },
        { by: "you",    t: "Blokirate vozilo kad zatreba", d: "Servis, registracija ili privatna upotreba. Označite vozilo kao nedostupno i ono se odmah sklanja iz ponude, bez ijedne izmjene na sajtu." },
      ],
      summary: "Vaš dio posla su dva klika. Sve ostalo sistem radi u pozadini, i dok spavate.",
    },
    howItWorks: {
      label: "Kako to radi",
      heading1: "Od upita do potvrde,",
      headingAccent: "bez vašeg trčanja",
      sub: "Cijeli tok traje manje od minute. Vi u njemu imate tačno jedan zadatak.",
      steps: [
        { t: "Gost rezerviše na vašem sajtu", d: "Bira datume i vozilo. Sistem prikazuje samo ono što je stvarno slobodno, pa zauzeto niko ne može tražiti." },
        { t: "Vama odmah stiže obavijest", d: "Na email i na telefon, sa svim podacima. Ne morate osvježavati sajt ni čekati poziv." },
        { t: "Potvrđujete iz panela", d: "Jedan klik. To je cijeli vaš dio posla oko jedne rezervacije." },
        { t: "Gost dobija potvrdu", d: "Automatski, s detaljima rezervacije. Vozilo se zaključava za te datume." },
      ],
      ui: {
        site: "vasa-firma.ba", calendar: "Odaberite datume", july: "Jul",
        bookBtn: "Rezerviši VW Golf 8", car: "VW Golf 8", price: "60 KM / dan",
        emailTitle: "Nova rezervacija", emailFrom: "sistem@vasa-firma.ba",
        emailBody: "VW Golf 8 · 10 do 13. jula · Mostar",
        tgApp: "Telegram", tgBody: "Imate novu rezervaciju na čekanju",
        panel: "Admin panel", pending: "Na čekanju", approveBtn: "Odobri", approved: "Odobreno",
        guest: "Amir H.", dates: "10 do 13. jula",
        phoneTitle: "Rezervacija potvrđena", phoneBody: "VW Golf 8, preuzimanje 10. jula u Mostaru",
        now: "sada",
      },
    },
    caseStudy: {
      label: "Primjer iz prakse",
      heading1: "Maximum Rent a Car,",
      headingAccent: "uživo u produkciji",
      desc: "Kompletan sistem za iznajmljivanje vozila koji radi svaki dan. Gost bira vozilo i datume, sistem provjerava dostupnost i sprječava dupla rezervisanja, a vlasnik sve potvrđuje iz svog panela.",
      stats: [
        { v: "100", l: "Google ocjena performansi" },
        { v: "3,2s", l: "učitavanje na telefonu, prije 21,6s" },
        { v: "2", l: "jezika, HR i EN" },
      ],
      note: "Brojke su Google PageSpeed mjerenja i možete ih ponoviti sami.",
      cta: "Otvorite sajt",
      ctaHref: "https://maximum-rent.vercel.app",
      imageAlt: "Maximum Rent a Car, naslovna stranica",
    },
    packages: {
      label: "Paketi",
      heading1: "Odaberite prema",
      headingAccent: "veličini flote",
      recommended: "Preporučeno",
      items: [
        {
          name: "Start", size: "3 do 9 vozila", price: "1.500 KM", priceNote: "jednokratno · oko €770",
          perDay: "oko 4 KM dnevno u prvoj godini",
          catch: "Izmjene vozila i cijena radimo mi i naplaćuju se po satu.",
          features: ["Sajt na jednom jeziku", "Katalog vozila s cijenama", "Forma za rezervaciju", "Prilagođeno telefonu", "Bez admin panela"],
          cta: "Zatražite ponudu",
        },
        {
          name: "Pro", size: "10 do 20 vozila", price: "2.900 KM", priceNote: "jednokratno · oko €1.480",
          perDay: "oko 8 KM dnevno u prvoj godini",
          bonus: "3 mjeseca besplatne podrške", bonusNote: "vrijednost €150",
          catch: "Sve mijenjate sami iz panela, bez dodatnih troškova.",
          features: ["Sve iz Start paketa", "Dvojezični sajt", "Admin panel za flotu i cijene", "Kalendar dostupnosti po vozilu", "Obavijesti o novom upitu"],
          cta: "Zatražite ponudu",
        },
        {
          name: "Premium", size: "20+ vozila, više lokacija", price: "4.200 KM", priceNote: "jednokratno · oko €2.150",
          perDay: "oko 11,50 KM dnevno u prvoj godini",
          bonus: "3 mjeseca besplatne podrške", bonusNote: "vrijednost €150",
          catch: "Za firme koje rade iz više poslovnica.",
          features: ["Sve iz Pro paketa", "Upravljanje po lokacijama", "Flota i preuzimanje po poslovnici", "Prioritetna podrška"],
          cta: "Zatražite ponudu",
        },
      ],
      note: "Mjesečno održavanje se dogovara zasebno i nije obavezno.",
      capacityLabel: "Veličina flote",
      afterHeading: "Nakon isporuke",
      afterSub: "Sistem je vaš i radi sam. Podršku birate onako kako vam odgovara.",
      support: {
        subLabel: "Mjesečna podrška",
        subPrice: "€50", subPer: "/mj",
        subDesc: "Do 8 sati mjesečno za izmjene, nadogradnje i pomoć kad nešto zapne. Javljam se prioritetno.",
        subAnchor: "Za poređenje, tih 8 sati po satnici bi bilo €200.",
        hourLabel: "Bez pretplate",
        hourPrice: "€25", hourPer: "/h",
        hourDesc: "Plaćate samo kada nešto zatreba, po utrošenom vremenu.",
        hostingNote: "Hosting se plaća zasebno, po stvarnoj potrošnji. Kod sajtova ove veličine to je vrlo mali iznos, a tačnu cifru vidite prije nego išta potpišete.",
      },
    },
    comparison: {
      label: "Pretplata ili vlasništvo",
      heading1: "Jednom platite,",
      headingAccent: "zauvijek je vaše",
      body: "Gotove platforme za ovu namjenu naplaćuju mjesečnu pretplatu dokle god ih koristite. Kod nas je to jednokratna investicija u sistem koji je vaš, uz održavanje koje se dogovara zasebno i može se prekinuti.",
      rows: [
        { a: "Mjesečna pretplata bez kraja", b: "Jednokratna investicija" },
        { a: "Sistem je njihov, vi ste korisnik", b: "Sistem i sajt su vaši" },
        { a: "Podaci o gostima na tuđem serveru", b: "Podaci ostaju kod vas" },
        { a: "Izgled i funkcije kakve daju svima", b: "Građeno oko vašeg načina rada" },
      ],
    },
    form: {
      label: "Upit",
      heading1: "Recite nam nešto",
      headingAccent: "o vašoj floti",
      sub: "Odgovorite na par pitanja i javljamo se s konkretnom ponudom. Traje oko dvije minute.",
      fleetSize: "Broj vozila",
      locations: "Broj lokacija",
      channels: "Kako sada primate rezervacije",
      channelsHint: "Možete označiti više odgovora",
      channelLabels: { telefon: "Telefon", "viber-whatsapp": "Viber ili WhatsApp", sajt: "Postojeći sajt", agregatori: "Agregatori", "walk-in": "Gost dođe lično" },
      aggregators: "Koristite li agregatore (Discover Cars, Rentalcars i slično)",
      yes: "Da", no: "Ne",
      currentSite: "Link postojećeg sajta",
      currentSiteHint: "Opcionalno",
      timeline: "Kada planirate krenuti",
      timelineLabels: { odmah: "Odmah", "prije-sezone": "Prije sezone", istrazujem: "Još istražujem" },
      contact: "Kontakt",
      fullName: "Ime i prezime",
      company: "Naziv firme",
      companyHint: "Opcionalno",
      phone: "Telefon",
      email: "Email",
      note: "Nešto dodatno",
      noteHint: "Opcionalno, do 500 znakova",
      directTitle: "Radije telefonom?",
      directSub: "Nazovite ili pišite na WhatsApp, javljamo se odmah.",
      callBtn: "Nazovite",
      waBtn: "WhatsApp",
      submit: "Pošaljite upit",
      submitting: "Šaljem…",
      choose: "Odaberite",
      successTitle: "Upit je stigao",
      successBody: "Javljamo vam odgovor u roku od 24 sata. Dotad možete pogledati Maximum Rent a Car, sistem koji smo gradili za istu vrstu posla.",
      successCta: "Pogledajte Maximum",
      errors: {
        required: "Ovo polje je obavezno",
        email: "Unesite ispravan email",
        url: "Unesite ispravan link, na primjer https://vasafirma.ba",
        max500: "Najviše 500 znakova",
        rate: "Previše pokušaja. Pokušajte ponovo za nekoliko minuta.",
        server: "Slanje trenutno ne radi. Pišite nam direktno na bakir.mehic@mehiccdev.com",
      },
    },
    faq: {
      label: "Česta pitanja",
      heading1: "Ono što nas",
      headingAccent: "najčešće pitaju",
      items: [
        { q: "Koliko traje izrada?", a: "Start paket obično dvije do tri sedmice od trenutka kada dobijemo podatke i fotografije. Pro i Premium traju duže jer imaju admin panel i kalendar. Tačan rok dobijate uz ponudu." },
        { q: "Šta je potrebno od vas?", a: "Popis vozila s cijenama, fotografije vozila i osnovni podaci firme. Ako nemate fotografije, dogovorimo snimanje. Sve ostalo radimo mi." },
        { q: "Može li se povezati s postojećim sajtom?", a: "Može. Sistem može zamijeniti postojeći sajt ili se dodati na vašu domenu kao poseban dio, ako želite zadržati ono što već imate." },
        { q: "Šta uključuje održavanje?", a: "Hosting, sigurnosne nadogradnje, backup i sitne izmjene u toku mjeseca. Dogovara se zasebno, nije obavezno i može se prekinuti." },
        { q: "Može li se plaćati u ratama?", a: "Da. Uobičajeno je pola na početku i pola na isporuci, a za veće pakete se može dogovoriti i drugačija dinamika." },
      ],
    },
  },

  en: {
    meta: {
      title: "Booking system for car rental companies | mehiccdev",
      description:
        "A web application for car rental companies: per vehicle availability calendar, admin panel for fleet and pricing, and a booking form. Car rental management software built in Mostar.",
    },
    nav: [
      { id: "problem",    label: "Problem" },
      { id: "rjesenje",   label: "Solution" },
      { id: "kako-radi",  label: "How it works" },
      { id: "case-study", label: "Example" },
      { id: "paketi",     label: "Packages" },
      { id: "poredjenje", label: "Comparison" },
      { id: "upit",       label: "Inquiry" },
      { id: "pitanja",    label: "Questions" },
    ],
    hero: {
      eyebrow: "Built for car rental companies",
      h1a: "A booking system",
      h1b: "for your car rental company",
      sub: "Website, admin panel and availability calendar in one. Guests check what is free and send a booking, you confirm it from your panel.",
      ctaPrimary: "Request a quote",
      ctaSecondary: "See the prices",
      points: ["No double bookings", "Works outside office hours", "The system stays yours"],
      demo: {
        window: "yourcompany.com", calendar: "Availability, July",
        car: "VW Golf 8", price: "€30 / day",
        free: "Available", booked: "Booked",
        newRequest: "New request", requestBody: "Booking July 10 to 13, pickup in Mostar",
        confirm: "Confirm", confirmed: "Confirmed", decline: "Decline",
      },
    },
    problem: {
      label: "How it works today",
      heading1: "You know",
      headingAccent: "this one",
      items: [
        { t: "Bookings arrive on Viber and by phone", d: "Everything is agreed through chat, while guest and date details stay scattered across messages and notebooks." },
        { t: "Aggregators take a commission", d: "Every booking through them cuts your margin, and the guest stays their customer, not yours." },
        { t: "Inquiries after hours go unanswered", d: "A guest who writes at eleven at night usually finds another company by morning." },
        { t: "Double bookings on the same vehicle", d: "When availability is tracked by hand, the same car easily gets promised to two guests." },
      ],
    },
    solution: {
      label: "What the system does",
      heading1: "One system instead of",
      headingAccent: "notebooks and chat",
      items: [
        { t: "Bilingual website", d: "Local and foreign guests read your offer in their own language, with no translating on the phone." },
        { t: "Availability calendar per vehicle", d: "The system blocks taken dates on its own, so double bookings cannot happen." },
        { t: "Admin panel for fleet and pricing", d: "You update vehicles, prices, photos and seasonal rates yourself, without calling a developer." },
        { t: "Booking form", d: "The guest sends a request with dates and location, you confirm it in two clicks." },
        { t: "Multi location management", d: "Several branches, each with its own fleet and pickup point." },
        { t: "SEO and speed", d: "The site loads fast and Google finds it easily, so new guests find you too." },
      ],
    },
    flow: {
      label: "How it works day to day",
      heading1: "The system works,",
      headingAccent: "you just decide",
      sub: "From inquiry to confirmed booking, the system handles every step on its own. Two things stay with you: accept or decline a booking, and block a vehicle when you need to.",
      bySystem: "System",
      byYou: "You",
      steps: [
        { by: "system", t: "The guest picks a vehicle and dates", d: "The system only shows vehicles that are genuinely free for those dates, so nobody can request a taken car." },
        { by: "system", t: "The inquiry reaches you instantly", d: "An alert by email and on your phone, with the vehicle, dates, location and guest contact. No copying details out of chats." },
        { by: "you",    t: "You accept or decline", d: "One click in the panel. That is your entire job for that booking." },
        { by: "system", t: "The rest happens on its own", d: "The dates lock, the vehicle disappears from the offer for that period, the guest gets a confirmation email and the calendar updates." },
        { by: "you",    t: "You block a vehicle when needed", d: "Servicing, registration or personal use. Mark the vehicle as unavailable and it leaves the offer straight away, with no changes to the website." },
      ],
      summary: "Your part is two clicks. Everything else runs in the background, including while you sleep.",
    },
    howItWorks: {
      label: "How it works",
      heading1: "From request to confirmation,",
      headingAccent: "without you running around",
      sub: "The whole flow takes less than a minute. You have exactly one job in it.",
      steps: [
        { t: "The guest books on your website", d: "They pick dates and a vehicle. The system only shows what is genuinely free, so nobody can request a taken car." },
        { t: "You get an alert straight away", d: "By email and on your phone, with all the details. No refreshing the site, no waiting for a call." },
        { t: "You confirm from the panel", d: "One click. That is your entire part of the job for that booking." },
        { t: "The guest gets a confirmation", d: "Automatically, with the booking details. The vehicle locks for those dates." },
      ],
      ui: {
        site: "yourcompany.com", calendar: "Pick your dates", july: "July",
        bookBtn: "Book VW Golf 8", car: "VW Golf 8", price: "€30 / day",
        emailTitle: "New booking request", emailFrom: "system@yourcompany.com",
        emailBody: "VW Golf 8 · July 10 to 13 · Mostar",
        tgApp: "Telegram", tgBody: "You have a new pending reservation",
        panel: "Admin panel", pending: "Pending", approveBtn: "Approve", approved: "Approved",
        guest: "Amir H.", dates: "July 10 to 13",
        phoneTitle: "Reservation confirmed", phoneBody: "VW Golf 8, pickup July 10 in Mostar",
        now: "now",
      },
    },
    caseStudy: {
      label: "A real example",
      heading1: "Maximum Rent a Car,",
      headingAccent: "live in production",
      desc: "A complete car rental system running every day. The guest picks a vehicle and dates, the system checks availability and prevents double bookings, and the owner confirms everything from the panel.",
      stats: [
        { v: "100", l: "Google performance score" },
        { v: "3.2s", l: "mobile load time, was 21.6s" },
        { v: "2", l: "languages, HR and EN" },
      ],
      note: "These are Google PageSpeed measurements and you can run them yourself.",
      cta: "Open the site",
      ctaHref: "https://maximum-rent.vercel.app",
      imageAlt: "Maximum Rent a Car home page",
    },
    packages: {
      label: "Packages",
      heading1: "Pick one by",
      headingAccent: "your fleet size",
      recommended: "Recommended",
      items: [
        {
          name: "Start", size: "3 to 9 vehicles", price: "€770", priceNote: "one time · 1,500 KM",
          perDay: "about €2.10 a day in the first year",
          catch: "We make vehicle and price changes for you, billed by the hour.",
          features: ["Single language website", "Vehicle catalogue with prices", "Booking form", "Built for phones", "No admin panel"],
          cta: "Request a quote",
        },
        {
          name: "Pro", size: "10 to 20 vehicles", price: "€1,480", priceNote: "one time · 2,900 KM",
          perDay: "about €4 a day in the first year",
          bonus: "3 months of free support", bonusNote: "€150 value",
          catch: "You change everything yourself from the panel, at no extra cost.",
          features: ["Everything in Start", "Bilingual website", "Admin panel for fleet and pricing", "Availability calendar per vehicle", "Alerts on every new inquiry"],
          cta: "Request a quote",
        },
        {
          name: "Premium", size: "20+ vehicles, several locations", price: "€2,150", priceNote: "one time · 4,200 KM",
          perDay: "about €5.90 a day in the first year",
          bonus: "3 months of free support", bonusNote: "€150 value",
          catch: "For companies working from several branches.",
          features: ["Everything in Pro", "Multi location management", "Fleet and pickup per branch", "Priority support"],
          cta: "Request a quote",
        },
      ],
      note: "Monthly maintenance is agreed separately and is optional.",
      capacityLabel: "Fleet size",
      afterHeading: "After launch",
      afterSub: "The system is yours and runs on its own. You pick the support that suits you.",
      support: {
        subLabel: "Monthly support",
        subPrice: "€50", subPer: "/mo",
        subDesc: "Up to 8 hours a month for changes, upgrades and help when something goes wrong. You get priority.",
        subAnchor: "For comparison, those 8 hours at the hourly rate would be €200.",
        hourLabel: "No subscription",
        hourPrice: "€25", hourPer: "/h",
        hourDesc: "You pay only when you need something, for the time spent.",
        hostingNote: "Hosting is billed separately, based on actual usage. For sites of this size it is a very small amount, and you see the exact figure before signing anything.",
      },
    },
    comparison: {
      label: "Subscription or ownership",
      heading1: "Pay once,",
      headingAccent: "it stays yours",
      body: "Ready made platforms for this purpose charge a monthly subscription for as long as you use them. With us it is a one time investment in a system that belongs to you, with maintenance agreed separately and cancellable.",
      rows: [
        { a: "A monthly fee with no end", b: "One time investment" },
        { a: "The system is theirs, you are a user", b: "The system and site are yours" },
        { a: "Guest data on someone else's server", b: "Your data stays with you" },
        { a: "The same look and features as everyone else", b: "Built around how you work" },
      ],
    },
    form: {
      label: "Inquiry",
      heading1: "Tell us a bit",
      headingAccent: "about your fleet",
      sub: "Answer a few questions and we will come back with a concrete quote. It takes about two minutes.",
      fleetSize: "Number of vehicles",
      locations: "Number of locations",
      channels: "How do you take bookings today",
      channelsHint: "You can pick more than one",
      channelLabels: { telefon: "Phone", "viber-whatsapp": "Viber or WhatsApp", sajt: "Existing website", agregatori: "Aggregators", "walk-in": "Walk in" },
      aggregators: "Do you use aggregators (Discover Cars, Rentalcars and similar)",
      yes: "Yes", no: "No",
      currentSite: "Link to your current website",
      currentSiteHint: "Optional",
      timeline: "When do you plan to start",
      timelineLabels: { odmah: "Right away", "prije-sezone": "Before the season", istrazujem: "Still looking around" },
      contact: "Contact",
      fullName: "Full name",
      company: "Company name",
      companyHint: "Optional",
      phone: "Phone",
      email: "Email",
      note: "Anything else",
      noteHint: "Optional, up to 500 characters",
      directTitle: "Prefer a call?",
      directSub: "Call us or send a WhatsApp message, we reply right away.",
      callBtn: "Call us",
      waBtn: "WhatsApp",
      submit: "Send inquiry",
      submitting: "Sending…",
      choose: "Choose",
      successTitle: "Your inquiry arrived",
      successBody: "We will get back to you within 24 hours. In the meantime you can look at Maximum Rent a Car, a system we built for the same kind of business.",
      successCta: "See Maximum",
      errors: {
        required: "This field is required",
        email: "Enter a valid email address",
        url: "Enter a valid link, for example https://yourcompany.com",
        max500: "500 characters maximum",
        rate: "Too many attempts. Please try again in a few minutes.",
        server: "Sending is not working right now. Write to us at bakir.mehic@mehiccdev.com",
      },
    },
    faq: {
      label: "Common questions",
      heading1: "What people",
      headingAccent: "ask us most",
      items: [
        { q: "How long does it take to build?", a: "The Start package usually takes two to three weeks from the moment we get your details and photos. Pro and Premium take longer because of the admin panel and calendar. You get an exact timeline with the quote." },
        { q: "What do you need from us?", a: "A list of vehicles with prices, vehicle photos and basic company details. If you do not have photos, we arrange a shoot. We handle the rest." },
        { q: "Can it work with our existing website?", a: "Yes. The system can replace your current site or sit on your domain as a separate part if you want to keep what you already have." },
        { q: "What does maintenance include?", a: "Hosting, security updates, backups and small changes during the month. It is agreed separately, it is optional and you can stop it." },
        { q: "Can we pay in instalments?", a: "Yes. It is usually half up front and half on delivery, and for larger packages we can agree on a different schedule." },
      ],
    },
  },
} as const;
