/**
 * components/rjesenja/rentACarCopy.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Sav tekst rent-a-car landing stranice, na oba jezika, na jednom mjestu.
 *
 * Zašto ovdje a ne u lib/i18n.ts: sve sekcije sajta drže svoj tekst uz sebe
 * (i18n.ts se više nigdje ne koristi), pa nova stranica prati istu konvenciju.
 * Fajl je običan TS bez "use client", pa ga može čitati i server komponenta
 * (metadata i JSON-LD) i klijentske sekcije.
 *
 * Pravila teksta: bez fraza, bez crtica, obraćanje vlasniku firme, riječ
 * "sistem" ili "aplikacija" umjesto "web stranica".
 */

export type RcCopy = (typeof COPY)["bs"] | (typeof COPY)["en"];

export const COPY = {
  bs: {
    meta: {
      title: "Rezervacioni sistem za rent-a-car firme | mehiccdev",
      description:
        "Web aplikacija za rent a car: kalendar dostupnosti po vozilu, admin panel za flotu i cijene i forma za rezervaciju. Sistem za iznajmljivanje vozila, građen u Mostaru.",
    },
    hero: {
      eyebrow: "Rješenje za rent-a-car firme",
      h1a: "Rezervacioni sistem",
      h1b: "za vašu rent-a-car firmu",
      sub: "Sajt, admin panel i kalendar dostupnosti u jednom. Gost sam provjeri šta je slobodno i pošalje rezervaciju, vi je potvrdite iz panela.",
      ctaPrimary: "Zatražite ponudu",
      ctaSecondary: "Pogledajte cijene",
      cardTitle: "Novi upit", cardBody: "VW Golf 8 · 10. do 13. jula", cardOk: "Potvrđeno, gost je dobio email",
      points: ["Bez duplih termina", "Radi i van radnog vremena", "Sistem ostaje vaš"],
    },
    compare: {
      label: "Razlika",
      heading1: "Jedna rezervacija,",
      headingAccent: "dva načina",
      sub: "Šta se dogodi kada gost želi vozilo, danas i sa sistemom.",
      tabOld: "Bez sistema",
      tabNew: "Sa sistemom",
      stepsTitleOld: "Kako to ide danas",
      stepsTitleNew: "Kako to ide sa sistemom",
      old: {
        steps: [
          { t: "Gost piše na Viber ili zove", d: "Ako ste na putu ili spavate, poruka čeka." },
          { t: "Tražite je li vozilo slobodno", d: "Po svesci, Excelu ili porukama od prošle sedmice." },
          { t: "Dogovarate se u nekoliko poruka", d: "Datumi, cijena, preuzimanje, sve ručno." },
          { t: "Upisujete rezervaciju", d: "I nadate se da niste isto vozilo već obećali." },
        ],
        stats: [
          { v: "15 min", l: "vašeg vremena po rezervaciji" },
          { v: "2 do 5 h", l: "dok gost dobije odgovor" },
          { v: "8 h", l: "koliko dnevno primate upite" },
          { v: "moguće", l: "dupli termini na istom vozilu" },
        ],
      },
      neu: {
        steps: [
          { t: "Gost bira datume na vašem sajtu", d: "Vidi samo ono što je stvarno slobodno." },
          { t: "Vama stiže obavijest", d: "Odmah, sa svim podacima, na email i telefon." },
          { t: "Potvrđujete jednim klikom", d: "To je cijeli vaš dio posla." },
          { t: "Gost dobija potvrdu", d: "Automatski, a vozilo se zaključa za te datume." },
        ],
        stats: [
          { v: "30 sek", l: "vašeg vremena po rezervaciji" },
          { v: "odmah", l: "dok gost dobije odgovor" },
          { v: "24 h", l: "koliko dnevno primate upite" },
          { v: "nemoguće", l: "dupli termini na istom vozilu" },
        ],
      },
      note: "Vremena su procjena za firmu koja rezervacije vodi ručno, radi poređenja. Vaš stvarni raspored može biti drugačiji.",
    },
    caseStudy: {
      label: "Primjer iz prakse",
      heading1: "Maximum Rent a Car,",
      headingAccent: "uživo u produkciji",
      desc: "Kompletan sistem za iznajmljivanje vozila koji radi svaki dan. Gost bira vozilo i datume, sistem provjerava dostupnost i sprječava dupla rezervisanja, a vlasnik sve potvrđuje iz svog panela.",
      stats: [
        { v: "100", l: "Google ocjena performansi" },
        { v: "3,2s", l: "učitavanje na telefonu, prije 21,6s" },
        { v: "2", l: "jezika, HR i EN" },
      ],
      note: "Brojke su Google PageSpeed mjerenja i možete ih ponoviti sami.",
      cta: "Otvorite sajt",
      caseLink: "Pročitajte cijeli primjer",
      ctaHref: "https://maximum-rent.vercel.app",
      imageAlt: "Maximum Rent a Car, naslovna stranica",
    },
    packages: {
      label: "Paketi",
      heading1: "Odaberite prema",
      headingAccent: "veličini flote",
      recommended: "Preporučeno",
      items: [
        {
          name: "Start", size: "3 do 9 vozila", price: "od 1.500 KM", priceNote: "jednokratno · oko €750",
          perDay: "oko 4 KM dnevno u prvoj godini",
          catch: "Izmjene vozila i cijena radimo mi i naplaćuju se po satu.",
          features: ["Sajt na jednom jeziku", "Katalog vozila s cijenama", "Forma za rezervaciju", "Prilagođeno telefonu", "Bez admin panela"],
          cta: "Zatražite ponudu",
        },
        {
          name: "Pro", size: "10 do 20 vozila", price: "od 2.600 KM", priceNote: "jednokratno · oko €1.330",
          perDay: "oko 7 KM dnevno u prvoj godini",
          bonus: "2 mjeseca besplatne podrške", bonusNote: "vrijednost 200 KM",
          catch: "Sve mijenjate sami iz panela, bez dodatnih troškova.",
          features: ["Sve iz Start paketa", "Dvojezični sajt", "Admin panel za flotu i cijene", "Kalendar dostupnosti po vozilu", "Obavijesti o novom upitu"],
          cta: "Zatražite ponudu",
        },
        {
          name: "Premium", size: "20+ vozila, više lokacija", price: "od 4.500 KM", priceNote: "jednokratno · oko €2.300",
          perDay: "oko 12,50 KM dnevno u prvoj godini",
          bonus: "2 mjeseca besplatne podrške", bonusNote: "vrijednost 200 KM",
          catch: "Za firme koje rade iz više poslovnica.",
          features: ["Sve iz Pro paketa", "Upravljanje po lokacijama", "Flota i preuzimanje po poslovnici", "Prioritetna podrška"],
          cta: "Zatražite ponudu",
        },
      ],
      note: "Mjesečno održavanje se dogovara zasebno i nije obavezno.",
      afterHeading: "Nakon isporuke",
      afterSub: "Sistem je vaš i radi sam. Podršku birate onako kako vam odgovara.",
      support: {
        subLabel: "Mjesečna podrška",
        subPrice: "100 KM", subPer: "/mj",
        subDesc: "Oko €50. Do 4 sata mjesečno za izmjene, nadogradnje i pomoć kad nešto zapne. Javljam se prioritetno.",
        subAnchor: "Za poređenje, ta 4 sata po satnici bi bila 200 KM.",
        hourLabel: "Bez pretplate",
        hourPrice: "50 KM", hourPer: "/h",
        hourDesc: "Oko €25. Plaćate samo kada nešto zatreba, po utrošenom vremenu.",
        hostingNote: "Hosting se plaća zasebno, po stvarnoj potrošnji. Kod sajtova ove veličine to je vrlo mali iznos, a tačnu cifru vidite prije nego išta potpišete.",
      },
    },
    comparison: {
      label: "Pretplata ili vlasništvo",
      colA: "Pretplata", colB: "Vlasništvo",
      heading1: "Jednom platite,",
      headingAccent: "zauvijek je vaše",
      body: "Gotove platforme za ovu namjenu naplaćuju mjesečnu pretplatu dokle god ih koristite. Kod nas je to jednokratna investicija u sistem koji je vaš, uz održavanje koje se dogovara zasebno i može se prekinuti.",
      rows: [
        { a: "Mjesečna pretplata bez kraja", b: "Jednokratna investicija" },
        { a: "Sistem je njihov, vi ste korisnik", b: "Sistem i sajt su vaši" },
        { a: "Podaci o gostima na tuđem serveru", b: "Podaci ostaju kod vas" },
        { a: "Izgled i funkcije kakve daju svima", b: "Građeno oko vašeg načina rada" },
      ],
    },
    form: {
      label: "Upit",
      heading1: "Recite nam nešto",
      headingAccent: "o vašoj floti",
      sub: "Odgovorite na par pitanja i javljamo se s konkretnom ponudom. Traje oko dvije minute.",
      fleetSize: "Broj vozila",
      timeline: "Kada planirate krenuti",
      timelineLabels: { odmah: "Odmah", "prije-sezone": "Prije sezone", istrazujem: "Još istražujem" },
      fullName: "Ime i prezime",
      company: "Naziv firme",
      companyHint: "Opcionalno",
      phone: "Telefon",
      email: "Email",
      note: "Nešto dodatno",
      noteHint: "Opcionalno, do 500 znakova",
      directTitle: "Radije telefonom?",
      directSub: "Nazovite ili pišite na WhatsApp, javljamo se odmah.",
      callBtn: "Nazovite",
      waBtn: "WhatsApp",
      submit: "Pošaljite upit",
      submitting: "Šaljem…",
      successTitle: "Upit je stigao",
      successBody: "Javljamo vam odgovor u roku od 24 sata. Dotad možete pogledati Maximum Rent a Car, sistem koji smo gradili za istu vrstu posla.",
      successCta: "Pogledajte Maximum",
      errors: {
        required: "Ovo polje je obavezno",
        email: "Unesite ispravan email",
        url: "Unesite ispravan link, na primjer https://vasafirma.ba",
        max500: "Najviše 500 znakova",
        rate: "Previše pokušaja. Pokušajte ponovo za nekoliko minuta.",
        server: "Slanje trenutno ne radi. Pišite nam direktno na bakir.mehic@mehiccdev.com",
      },
    },
    faq: {
      label: "Česta pitanja",
      heading1: "Ono što nas",
      headingAccent: "najčešće pitaju",
      items: [
        { q: "Koliko traje izrada?", a: "Start paket obično dvije do tri sedmice od trenutka kada dobijemo podatke i fotografije. Pro i Premium traju duže jer imaju admin panel i kalendar. Tačan rok dobijate uz ponudu." },
        { q: "Šta je potrebno od vas?", a: "Popis vozila s cijenama, fotografije vozila i osnovni podaci firme. Ako nemate fotografije, dogovorimo snimanje. Sve ostalo radimo mi." },
        { q: "Može li se povezati s postojećim sajtom?", a: "Može. Sistem može zamijeniti postojeći sajt ili se dodati na vašu domenu kao poseban dio, ako želite zadržati ono što već imate." },
        { q: "Šta uključuje održavanje?", a: "Hosting, sigurnosne nadogradnje, backup i sitne izmjene u toku mjeseca. Dogovara se zasebno, nije obavezno i može se prekinuti." },
        { q: "Može li se plaćati u ratama?", a: "Da. Uobičajeno je pola na početku i pola na isporuci, a za veće pakete se može dogovoriti i drugačija dinamika." },
      ],
    },
  },

  en: {
    meta: {
      title: "Booking system for car rental companies | mehiccdev",
      description:
        "A web application for car rental companies: per vehicle availability calendar, admin panel for fleet and pricing, and a booking form. Car rental management software built in Mostar.",
    },
    hero: {
      eyebrow: "Built for car rental companies",
      h1a: "A booking system",
      h1b: "for your car rental company",
      sub: "Website, admin panel and availability calendar in one. Guests check what is free and send a booking, you confirm it from your panel.",
      ctaPrimary: "Request a quote",
      ctaSecondary: "See the prices",
      cardTitle: "New inquiry", cardBody: "VW Golf 8 · July 10 to 13", cardOk: "Confirmed, the guest got an email",
      points: ["No double bookings", "Works outside office hours", "The system stays yours"],
    },
    compare: {
      label: "The difference",
      heading1: "One booking,",
      headingAccent: "two ways",
      sub: "What happens when a guest wants a car, today and with the system.",
      tabOld: "Without the system",
      tabNew: "With the system",
      stepsTitleOld: "How it goes today",
      stepsTitleNew: "How it goes with the system",
      old: {
        steps: [
          { t: "The guest messages or calls", d: "If you are driving or asleep, the message waits." },
          { t: "You check if the car is free", d: "In a notebook, a spreadsheet or last week's messages." },
          { t: "You agree over several messages", d: "Dates, price, pickup, all by hand." },
          { t: "You write the booking down", d: "And hope you have not promised the same car twice." },
        ],
        stats: [
          { v: "15 min", l: "of your time per booking" },
          { v: "2 to 5 h", l: "until the guest hears back" },
          { v: "8 h", l: "a day you can take requests" },
          { v: "possible", l: "double bookings on one vehicle" },
        ],
      },
      neu: {
        steps: [
          { t: "The guest picks dates on your site", d: "They only see what is genuinely free." },
          { t: "You get an alert", d: "Instantly, with all details, by email and on your phone." },
          { t: "You confirm in one click", d: "That is your entire part of the job." },
          { t: "The guest gets a confirmation", d: "Automatically, and the vehicle locks for those dates." },
        ],
        stats: [
          { v: "30 sec", l: "of your time per booking" },
          { v: "instant", l: "until the guest hears back" },
          { v: "24 h", l: "a day you can take requests" },
          { v: "impossible", l: "double bookings on one vehicle" },
        ],
      },
      note: "These times are an estimate for a company handling bookings by hand, shown for comparison. Your actual routine may differ.",
    },
    caseStudy: {
      label: "A real example",
      heading1: "Maximum Rent a Car,",
      headingAccent: "live in production",
      desc: "A complete car rental system running every day. The guest picks a vehicle and dates, the system checks availability and prevents double bookings, and the owner confirms everything from the panel.",
      stats: [
        { v: "100", l: "Google performance score" },
        { v: "3.2s", l: "mobile load time, was 21.6s" },
        { v: "2", l: "languages, HR and EN" },
      ],
      note: "These are Google PageSpeed measurements and you can run them yourself.",
      cta: "Open the site",
      caseLink: "Read the full case study",
      ctaHref: "https://maximum-rent.vercel.app",
      imageAlt: "Maximum Rent a Car home page",
    },
    packages: {
      label: "Packages",
      heading1: "Pick one by",
      headingAccent: "your fleet size",
      recommended: "Recommended",
      items: [
        {
          name: "Start", size: "3 to 9 vehicles", price: "from €750", priceNote: "one time · 1,500 KM",
          perDay: "about €2 a day in the first year",
          catch: "We make vehicle and price changes for you, billed by the hour.",
          features: ["Single language website", "Vehicle catalogue with prices", "Booking form", "Built for phones", "No admin panel"],
          cta: "Request a quote",
        },
        {
          name: "Pro", size: "10 to 20 vehicles", price: "from €1,330", priceNote: "one time · 2,600 KM",
          perDay: "about €3.60 a day in the first year",
          bonus: "2 months of free support", bonusNote: "€100 value",
          catch: "You change everything yourself from the panel, at no extra cost.",
          features: ["Everything in Start", "Bilingual website", "Admin panel for fleet and pricing", "Availability calendar per vehicle", "Alerts on every new inquiry"],
          cta: "Request a quote",
        },
        {
          name: "Premium", size: "20+ vehicles, several locations", price: "from €2,300", priceNote: "one time · 4,500 KM",
          perDay: "about €6.30 a day in the first year",
          bonus: "2 months of free support", bonusNote: "€100 value",
          catch: "For companies working from several branches.",
          features: ["Everything in Pro", "Multi location management", "Fleet and pickup per branch", "Priority support"],
          cta: "Request a quote",
        },
      ],
      note: "Monthly maintenance is agreed separately and is optional.",
      afterHeading: "After launch",
      afterSub: "The system is yours and runs on its own. You pick the support that suits you.",
      support: {
        subLabel: "Monthly support",
        subPrice: "€50", subPer: "/mo",
        subDesc: "About 100 KM. Up to 4 hours a month for changes, upgrades and help when something goes wrong. You get priority.",
        subAnchor: "For comparison, those 4 hours at the hourly rate would be €100.",
        hourLabel: "No subscription",
        hourPrice: "€25", hourPer: "/h",
        hourDesc: "About 50 KM. You pay only when you need something, for the time spent.",
        hostingNote: "Hosting is billed separately, based on actual usage. For sites of this size it is a very small amount, and you see the exact figure before signing anything.",
      },
    },
    comparison: {
      label: "Subscription or ownership",
      colA: "Subscription", colB: "Ownership",
      heading1: "Pay once,",
      headingAccent: "it stays yours",
      body: "Ready made platforms for this purpose charge a monthly subscription for as long as you use them. With us it is a one time investment in a system that belongs to you, with maintenance agreed separately and cancellable.",
      rows: [
        { a: "A monthly fee with no end", b: "One time investment" },
        { a: "The system is theirs, you are a user", b: "The system and site are yours" },
        { a: "Guest data on someone else's server", b: "Your data stays with you" },
        { a: "The same look and features as everyone else", b: "Built around how you work" },
      ],
    },
    form: {
      label: "Inquiry",
      heading1: "Tell us a bit",
      headingAccent: "about your fleet",
      sub: "Answer a few questions and we will come back with a concrete quote. It takes about two minutes.",
      fleetSize: "Number of vehicles",
      timeline: "When do you plan to start",
      timelineLabels: { odmah: "Right away", "prije-sezone": "Before the season", istrazujem: "Still looking around" },
      fullName: "Full name",
      company: "Company name",
      companyHint: "Optional",
      phone: "Phone",
      email: "Email",
      note: "Anything else",
      noteHint: "Optional, up to 500 characters",
      directTitle: "Prefer a call?",
      directSub: "Call us or send a WhatsApp message, we reply right away.",
      callBtn: "Call us",
      waBtn: "WhatsApp",
      submit: "Send inquiry",
      submitting: "Sending…",
      successTitle: "Your inquiry arrived",
      successBody: "We will get back to you within 24 hours. In the meantime you can look at Maximum Rent a Car, a system we built for the same kind of business.",
      successCta: "See Maximum",
      errors: {
        required: "This field is required",
        email: "Enter a valid email address",
        url: "Enter a valid link, for example https://yourcompany.com",
        max500: "500 characters maximum",
        rate: "Too many attempts. Please try again in a few minutes.",
        server: "Sending is not working right now. Write to us at bakir.mehic@mehiccdev.com",
      },
    },
    faq: {
      label: "Common questions",
      heading1: "What people",
      headingAccent: "ask us most",
      items: [
        { q: "How long does it take to build?", a: "The Start package usually takes two to three weeks from the moment we get your details and photos. Pro and Premium take longer because of the admin panel and calendar. You get an exact timeline with the quote." },
        { q: "What do you need from us?", a: "A list of vehicles with prices, vehicle photos and basic company details. If you do not have photos, we arrange a shoot. We handle the rest." },
        { q: "Can it work with our existing website?", a: "Yes. The system can replace your current site or sit on your domain as a separate part if you want to keep what you already have." },
        { q: "What does maintenance include?", a: "Hosting, security updates, backups and small changes during the month. It is agreed separately, it is optional and you can stop it." },
        { q: "Can we pay in instalments?", a: "Yes. It is usually half up front and half on delivery, and for larger packages we can agree on a different schedule." },
      ],
    },
  },
} as const;
